// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKDN14WmF5z1k8jd4eygafKKG9Xm3mJ0',
    appId: '1:278902939143:web:189476701e7abcfdd414a2',
    messagingSenderId: '278902939143',
    projectId: 'cuidadoamigo-f22cd',
    authDomain: 'cuidadoamigo-f22cd.firebaseapp.com',
    storageBucket: 'cuidadoamigo-f22cd.appspot.com',
    measurementId: 'G-2YW18JCCQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbD2xTjVNCb6vAoPSwcKeAwknvpjG3z9Y',
    appId: '1:278902939143:android:f61ae6e72542cab6d414a2',
    messagingSenderId: '278902939143',
    projectId: 'cuidadoamigo-f22cd',
    storageBucket: 'cuidadoamigo-f22cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznOrNvKoUJQXo5I2QjqlBocOwloOWIq8',
    appId: '1:278902939143:ios:a4098bce977535f8d414a2',
    messagingSenderId: '278902939143',
    projectId: 'cuidadoamigo-f22cd',
    storageBucket: 'cuidadoamigo-f22cd.appspot.com',
    iosClientId: '278902939143-4usug0obe7s4s26uvmbjl2oep65kf8r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuidadoamigoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAznOrNvKoUJQXo5I2QjqlBocOwloOWIq8',
    appId: '1:278902939143:ios:83c3cd2ca956349ed414a2',
    messagingSenderId: '278902939143',
    projectId: 'cuidadoamigo-f22cd',
    storageBucket: 'cuidadoamigo-f22cd.appspot.com',
    iosClientId: '278902939143-ndgi4vgm13glh9d58offrp6vdin2lild.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuidadoamigoapp.RunnerTests',
  );
}
