// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCox7ZGwJyoEF9QOTJWMpjDSWkpb9j5qLM',
    appId: '1:553835935461:web:3e3f3b2d690b8a257d060c',
    messagingSenderId: '553835935461',
    projectId: 'cuidado-amigo-7b432',
    authDomain: 'cuidado-amigo-7b432.firebaseapp.com',
    storageBucket: 'cuidado-amigo-7b432.appspot.com',
    measurementId: 'G-WYXSJZXRYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdlFaFEfM-YnygxZWtO3Hh_a9c3EjGpwg',
    appId: '1:553835935461:android:8fb67cb019704aea7d060c',
    messagingSenderId: '553835935461',
    projectId: 'cuidado-amigo-7b432',
    storageBucket: 'cuidado-amigo-7b432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApgnrBOI5-pR1HKh5JHYJYxfkrEvgorMM',
    appId: '1:553835935461:ios:23cf2593124e05ba7d060c',
    messagingSenderId: '553835935461',
    projectId: 'cuidado-amigo-7b432',
    storageBucket: 'cuidado-amigo-7b432.appspot.com',
    iosBundleId: 'com.example.cuidadoamigoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApgnrBOI5-pR1HKh5JHYJYxfkrEvgorMM',
    appId: '1:553835935461:ios:23cf2593124e05ba7d060c',
    messagingSenderId: '553835935461',
    projectId: 'cuidado-amigo-7b432',
    storageBucket: 'cuidado-amigo-7b432.appspot.com',
    iosBundleId: 'com.example.cuidadoamigoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCox7ZGwJyoEF9QOTJWMpjDSWkpb9j5qLM',
    appId: '1:553835935461:web:2fd33d3e3ee36d4e7d060c',
    messagingSenderId: '553835935461',
    projectId: 'cuidado-amigo-7b432',
    authDomain: 'cuidado-amigo-7b432.firebaseapp.com',
    storageBucket: 'cuidado-amigo-7b432.appspot.com',
    measurementId: 'G-6FHYBPBN6Q',
  );
}
