// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJ0AJtkn-4_Db9JzolS9PBHj092q3U_Y',
    appId: '1:197085834512:web:11de69c16c348f8d068995',
    messagingSenderId: '197085834512',
    projectId: 'cuidado-amigo-384d3',
    authDomain: 'cuidado-amigo-384d3.firebaseapp.com',
    storageBucket: 'cuidado-amigo-384d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpeulQppT3UQGFM_JAw976nvDwlFmXEg',
    appId: '1:197085834512:android:d66bb5ca3b87400f068995',
    messagingSenderId: '197085834512',
    projectId: 'cuidado-amigo-384d3',
    storageBucket: 'cuidado-amigo-384d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYzg_RGQDDbOFBUbzx20H5Tc1NTUM6oo',
    appId: '1:197085834512:ios:bbf20616e48eff6f068995',
    messagingSenderId: '197085834512',
    projectId: 'cuidado-amigo-384d3',
    storageBucket: 'cuidado-amigo-384d3.firebasestorage.app',
    iosBundleId: 'com.example.cuidadoamigoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYzg_RGQDDbOFBUbzx20H5Tc1NTUM6oo',
    appId: '1:197085834512:ios:bbf20616e48eff6f068995',
    messagingSenderId: '197085834512',
    projectId: 'cuidado-amigo-384d3',
    storageBucket: 'cuidado-amigo-384d3.firebasestorage.app',
    iosBundleId: 'com.example.cuidadoamigoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPJ0AJtkn-4_Db9JzolS9PBHj092q3U_Y',
    appId: '1:197085834512:web:0b8ae14542c4b004068995',
    messagingSenderId: '197085834512',
    projectId: 'cuidado-amigo-384d3',
    authDomain: 'cuidado-amigo-384d3.firebaseapp.com',
    storageBucket: 'cuidado-amigo-384d3.firebasestorage.app',
  );
}
